### ISSUE TITLE
The scene wont load

### ISSUE THREAD

**Issue by SupremeSugoma** [sdsgisd/HGF#2]
All I get is a wireframe render without any texture
![Screenshot from 2024-05-21 11-28-12](https://github.com/sdsgisd/HGF/assets/154726152/f07db4f7-3ef1-4bad-8b75-7e190e8ff4a5)
Help please

**Comment by sdsgisd** [comment]
Press 'm' to change the rendering mode.

**Comment by sdsgisd** [comment]
Solved.

**Comment by SupremeSugoma** [comment]
I want it to look like a transparent soap bubble as it shown in the images of this repository.  Can this be done? There is a folder named textures that contain png images and I am guessing that those images would serve as a background.  Can this be done?
Thank you.

**Comment by sdsgisd** [comment]
No unfortunately this is far outside the scope of this repository. As written in the paper, we rendered it by customizing Mitsuba renderer, but we are not publicizing the code for this as it depends on the versions of many dependencies of mitsuba. And as far as I know real-time photorealistic rendering of thin-film interference has never been achieved in graphics. But you can at least make your bubbles half transparent by changing the rendering mode as written in README. Did you really try it?

**Comment by SupremeSugoma** [comment]
I did try it... The fact that It isn't possible to have real time simulation as shown in the video isn't a disappointment but a surprise, and also a matter of hope that it would be possible one day. 
Thank you.

**Comment by SupremeSugoma** [comment]
Also, I'd like to inform you that the current version of libigl doesn't work. I had to use an older release version.
